### ISSUE TITLE
"cannot allocate memory" error on LPC when following documentation example

### ISSUE THREAD

**Issue by afrankenthal** [scikit-hep/coffea#115] opened 2019-06-17 18:19 UTC
I copied the first 4 blocks of code from the [documentation](https://coffeateam.github.io/coffea/coffea-introduction.html) onto a jupyter notebook running on LPC nodes. Whenever I try to execute run_uproot_job, I get a "cannot allocate memory" error. After some initial debugging, I've updated all the dependencies to the latest versions but the error persists. I also tried with two different users in the LPC with the same error. Screenshots of the error below:

![image](https://user-images.githubusercontent.com/16767477/59626795-690e0780-9102-11e9-8b81-f985f2be82bb.png)

![image](https://user-images.githubusercontent.com/16767477/59626809-70cdac00-9102-11e9-80d8-652933ab1fe5.png)

**Comment by lgray** [comment] 2019-06-17 18:54
@afrankenthal Hey, thanks for posting this. Can you try putting the rest file into eos and reading through xrootd? It seems like there may be something funny with mmap on the LPC.

Similarly, can you try this on slc7 to make sure it's not slc6 specific?

**Comment by afrankenthal** [comment] 2019-06-17 19:33
@lgray slc7 didn't make a difference but putting the input files on EOS does seem to do the trick! I tried both iterative and future executors and both worked. Last week I had tried my own files on EOS and was getting a different error (because of my own misunderstanding) but it masked the mmap issue on the LPC.

**Comment by lgray** [comment] 2019-06-17 19:50
@afrankenthal OK, interesting that the error remains on both. Can you try it quickly on your laptop to see if it functions there? Just trying to map out where things work and where they don't.

Good that local at the LPC functions!

**Comment by afrankenthal** [comment] 2019-06-17 21:16
Ok, here's the summary so far:

- LPC:
  - sl6:
    - local: **"cannot allocate memory"**
    - xrootd: **works**
  - sl7:
    - local: **"cannot allocate memory"**
    - xrootd: **works**
- macOS:
  - Sierra (10.12):
    - local: **works**
    - xrootd: **works**

**Comment by nsmith-** [comment] 2019-06-17 22:50
Nice test matrix!
To add, I reconfigured coffea to use different uproot sources:

- MemmapSource from NFS mount: **cannot allocate**
- MemmapSource from EOS mount: **cannot allocate**
- MemmapSource from `/tmp` mount: **cannot allocate**
- FileSource from NFS mount with `parallel=None`: **ok**

The strange thing is the total size of files is ~7 GB but `htop` shows _virtual_ memory usage per process up to 15+ GB.  Some sort of 'leak' of `np.memmap` ? @jpivarski fyi

**Comment by nsmith-** [comment] 2019-06-17 23:09
Yeah, so mmap does not alias, even when they're all read-only.  Even though the memory is _virtual_, it still counts against the virtual memory limit in the OS, namely `ulimit -v`. (16 GB on LPC)
Hence for some suitable choice of `i`, 
```python
a = [np.memmap('data/Run2012C_DoubleMuParked.root', mode='r') for _ in range(i)]
```
will cause `OSError: [Errno 12] Cannot allocate memory`

Amusingly, on my mac, `ulimit -v` returns `unlimited` :sunglasses:

**Comment by nsmith-** [comment] 2019-06-17 23:16
Since we iterate in chunks over the files, we rely on python to quickly garbage-collect the memmaps.  Since python makes no guarantee about how quickly it does so, occasionally the memmaps will stay around too long and produce OOM errors.
There's no way to share a memmap across the process pool either, as far as I can tell.

**Comment by afrankenthal** [comment] 2019-06-17 23:20
Interesting! Is there a way to estimate a safe max chunk size such that it will be unlikely to produce OOM? Though that will depend on the user system I suppose. My naive guess would be the total memory / number of workers?

**Comment by afrankenthal** [comment] 2019-06-17 23:20
Mine also says unlimited! And it's a 2013 macbook air... :)

**Comment by nsmith-** [comment] 2019-06-17 23:23
This issue is independent of chunk size.  It depends on the file size itself, and how many `np.memmap()` instances are active in a process at a given time.  I'll add a switch to use the non-memmaped file source for now, and we'll see how that goes.

**Comment by jpivarski** [comment] 2019-06-17 23:24
(My Linux ulimit is unlimited also; it's a choice. The disadvantage is the possibility of swapping, something that's more tolerable on user-interface systems than batch processors.)

Do you need a way to explicitly close memmaps? The reason uproot doesn't do that is because accessing the array after closing causes a segmentation fault, and segmentation faults are to be avoided at all costs in Python (no way to diagnose them).

See https://github.com/scikit-hep/uproot/blob/master/uproot/source/memmap.py

The `dismiss` method is always (_should_ always be) called after some operation, such as reading an array. Even if the user does some complex read of many arrays in parallel, `dismiss` should be called once at the end of all of that, after everything is done. Then the `data` method is the only way anything gets read, so it would be possible to close the file in `dismiss` and re-open it before any reading occurs in `data`. The non-memmap sources already work like that.

Such a thing could become a non-standard parameter for `MemmapSource`, like `closeOnDismiss=True` (with `False` being the default).

**Comment by nsmith-** [comment] 2019-06-17 23:31
I wouldn't want to close/open at each access, that sounds like too much syscall.  This is probably another instance where `with` semantics solve the problem nicely.  I would wrap the whole file processing in a `with` block and then it can be guaranteed to be cleaned up at the end.

However, I think the unfortunate fact that there is a rather low `ulimit -v` at LPC means that mmap users will often hit this issue, if they have large files.

**Comment by jpivarski** [comment] 2019-06-17 23:44
Perhaps it could have its current behavior in the absence of a `with` block (none of my tutorial or documentation examples encourage `with` semantics of uproot files) and _if_ somebody uses a `with` block (a `ROOTDirectory` gets an `__exit__` call, [currently pass-through](https://github.com/scikit-hep/uproot/blob/master/uproot/rootio.py#L356)), _then_ it would do the new behavior of close on `dismiss`, open on `data`?

I'm wondering if you'd like to try that on your example at the LPC to find out if it would help, and if so, we could make it a new uproot feature.

(Apparently, I need to detect whether a file is on NFS or not, or any other non-memmappable filesystem, to determine whether to switch to a `FileSource`. Also, I should turn off the `parallel` default if it's not working.)

**Comment by nsmith-** [comment] 2019-06-17 23:49
I think if an `__exit__` is called on `ROOTDirectory`, no further interaction should be allowed with it.  

Regarding the last point, NFS is mmap-able, I don't think this issue depends on the filesystem.  At least the three types I tried all had the same behavior.

**Comment by jpivarski** [comment] 2019-06-17 23:59
Oh, I'd heard that NFS isn't mmap-able, and I thought you just confirmed it above.

Then the new behavior would be `ROOTDirectory.__exit__` closes the mmap (maybe set its `_source` to `None`) and subsequent calls to `data` check for closed and raise an exception with a proper error message. The important thing is that it is protected against segmentation faults. (That's another good argument for `memmapsource._source.close()` to be immediately followed by `memmapsource._source = None`; at worst, subsequent access would be an exception from trying to do things to `None`, not a segmentation fault, though that wouldn't be a very helpful error message.)

**Comment by lgray** [comment] 2019-06-18 01:45
@jpivarski what would be the appropriate package to test against this in? coffea seems to high-level but it's also an entry point to a growing number of people.

**Comment by jpivarski** [comment] 2019-06-18 02:10
What I was thinking was to run your standard suite on LPC with a custom uproot that closes memmap files.

The first thing we could try is the `dismiss`/`data` pair (a non-default parameter to `uproot.open` that eagerly closes memmaps). @nsmith- was concerned about the number of system calls, but it's not obvious to me that it would be a bottleneck. Your LPC test suite would have to explicitly set `closeOnDismiss=True` in `uproot.open`.

The second thing to try would be to have `ROOTDirectory.__exit__` close memmap files, careful to set the `_source` to `None` and raise exceptions, rather than segmentation faults. That would require more intervention on the part of your calling code—you'd have to use `with` semantics to enable it.

I could put the first modification into an uproot PR, if you're in a position to get uproot that way into your tests. Otherwise, I'd have to create release candidates on PyPI and the testing cycle would be longer.

**Comment by nsmith-** [comment] 2019-06-18 03:03
Well since the source base class has `close()` I went ahead and added a `file.source.close()` call after processing the chunk and that makes sure only one mmap per process is active.  This alleviates the issue.  Comparing mmap to non-mmap, there isn't really any performance difference with the lazy fetching.

**Comment by jpivarski** [comment] 2019-06-18 12:06
I forgot that `MemmapSource.close` [was in there](https://github.com/scikit-hep/uproot/blob/master/uproot/source/memmap.py#L33-L34). At the very least, I need to follow `self._source._mmap.close()` with `self._source = None`.

The reason I wanted to try a test with `dismiss`/`data` closing and reopening memmaps is because I won't know if it's a scalable solution until I see what happens in your big tests. I don't have a realistic testing case.

**Closed as completed** 2019-06-25 06:25 UTC
Labels: bug
