### ISSUE TITLE
Reading data with Coffea NanoEvents terminates with and AttributeError

### ISSUE THREAD

**Issue by hephysicist** [scikit-hep/coffea#766] opened 2023-02-28 16:54 UTC
**Describe the bug**
The latest coffea (0.7.15) release seems to have broken dependencies with uproot. The example from [nanoevents.ipynb](https://github.com/CoffeaTeam/coffea/blob/master/binder/nanoevents.ipynb) fails to upload the root file. 

**Code example**
```
import awkward as ak
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

fname = "https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root(
    fname,
    schemaclass=NanoAODSchema.v6,
    metadata={"dataset": "DYJets"},
).events()
```

**Output**
```
(cp_env) bash-4.2$ python coffea_test.py
Traceback (most recent call last):
  File "coffea_test.py", line 5, in <module>
    events = NanoEventsFactory.from_root(
  File "/nfs/dust/cms/user/stzakhar/miniconda3/envs/cp_env/lib/python3.8/site-packages/coffea/nanoevents/factory.py", line 124, in from_root
    base_form = mapping._extract_base_form(
  File "/nfs/dust/cms/user/stzakhar/miniconda3/envs/cp_env/lib/python3.8/site-packages/coffea/nanoevents/mapping/uproot.py", line 105, in _extract_base_form
    form = uproot._util.awkward_form_remove_uproot(awkward, form)
AttributeError: module 'uproot._util' has no attribute 'awkward_form_remove_uproot'
```
**Package versions**
I ran the code on Python 3.8.15 using coffea 0.7.15,  uproot  5.0.3, awkward 2.0.8. Downgrading coffea to 0.7.12 didn't make any effect.

**Comment by lgray** [comment] 2023-02-28 17:26
Coffea 0.7.x releases are not compatible with uproot5 or awkward2. Please downgrade to the latest uproot4 and awkward1.

Coffea 0.7.15 is not the latest release (it is 0.7.20), the latest release implements dependency guards.

**Comment by lgray** [comment] 2023-02-28 17:49
Closing this issue - it is not a bug.

**Closed as completed by lgray** 2023-02-28 17:49 UTC
Labels: invalid, dependencies
